// Mapeamento entre o status de exibição da UI ("CADASTRO INICIAL") e o enum do
// banco (CADASTRO_INICIAL). Módulo client-safe (sem Prisma) — usado pelo serviço
// (servidor) e pelo mapper de leitura (cliente).

import type { ProjectStatus as UiStatus } from "./project-types";

export type DbStatus =
  | "CADASTRO_INICIAL"
  | "ELABORAR_ANTE_PROJETO"
  | "ANTE_PROJETO_ENVIADO"
  | "REVISAO_DE_ESTUDO"
  | "ANTE_PROJETO_APROVADO"
  | "PROJETO_APROVADO"
  | "PROJETO_FINAL_ENVIADO"
  | "REVISAO_DE_PROJETO_FINAL";

export const UI_TO_DB_STATUS: Record<UiStatus, DbStatus> = {
  "CADASTRO INICIAL": "CADASTRO_INICIAL",
  "ELABORAR ANTE-PROJETO": "ELABORAR_ANTE_PROJETO",
  "ANTE-PROJETO ENVIADO": "ANTE_PROJETO_ENVIADO",
  "ANTE-PROJETO APROVADO": "ANTE_PROJETO_APROVADO",
  "PROJETO APROVADO": "PROJETO_APROVADO",
  "PROJETO FINAL ENVIADO": "PROJETO_FINAL_ENVIADO",
  "REVISAO DE ESTUDO": "REVISAO_DE_ESTUDO",
  "REVISAO DE PROJETO FINAL": "REVISAO_DE_PROJETO_FINAL",
};

export const DB_TO_UI_STATUS: Record<DbStatus, UiStatus> = {
  CADASTRO_INICIAL: "CADASTRO INICIAL",
  ELABORAR_ANTE_PROJETO: "ELABORAR ANTE-PROJETO",
  ANTE_PROJETO_ENVIADO: "ANTE-PROJETO ENVIADO",
  ANTE_PROJETO_APROVADO: "ANTE-PROJETO APROVADO",
  PROJETO_APROVADO: "PROJETO APROVADO",
  PROJETO_FINAL_ENVIADO: "PROJETO FINAL ENVIADO",
  REVISAO_DE_ESTUDO: "REVISAO DE ESTUDO",
  REVISAO_DE_PROJETO_FINAL: "REVISAO DE PROJETO FINAL",
};

// Transições permitidas (espelha ALLOWED_TRANSITIONS do domínio, em enum do banco).
export const ALLOWED_DB_TRANSITIONS: Record<DbStatus, DbStatus[]> = {
  CADASTRO_INICIAL: ["ELABORAR_ANTE_PROJETO"],
  ELABORAR_ANTE_PROJETO: ["ANTE_PROJETO_ENVIADO"],
  ANTE_PROJETO_ENVIADO: ["ANTE_PROJETO_APROVADO", "REVISAO_DE_ESTUDO"],
  REVISAO_DE_ESTUDO: ["ANTE_PROJETO_ENVIADO"],
  ANTE_PROJETO_APROVADO: ["PROJETO_APROVADO"],
  PROJETO_APROVADO: ["PROJETO_FINAL_ENVIADO"],
  PROJETO_FINAL_ENVIADO: ["REVISAO_DE_PROJETO_FINAL"],
  REVISAO_DE_PROJETO_FINAL: ["PROJETO_FINAL_ENVIADO"],
};

// Prazo externo (dias) por status. Demais status não têm prazo.
export const DB_STATUS_DEADLINE_DAYS: Partial<Record<DbStatus, number>> = {
  ELABORAR_ANTE_PROJETO: 45,
  REVISAO_DE_ESTUDO: 20,
  REVISAO_DE_PROJETO_FINAL: 20,
};
